version: "3"
services:
  app:
    build: .
    ports:
      - 8050:8050
    command: npm run start
    volumes:
      - ./src:/app/src
    tty: true
  test:
    build: .
    command: npm run test
    volumes:
      - ./src:/app/src
    tty: true
